version: build{build}
image: Visual Studio 2015
configuration: Release
platform: x64
  
environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
      MSYS_BASE: C:\MinGW\msys\1.0
      MSYS_BASE_BIN: C:\MinGW\msys\1.0
      MINGW_BASE: C:\MinGW
    - TEST_INTERVAL_LIB: "filib"
      MSYS_BASE: C:\MinGW\msys\1.0
      MSYS_BASE_BIN: C:\MinGW\msys\1.0
      MINGW_BASE: C:\MinGW
    - TESTINTERVAL_LIB: "filib"
      MSYS_BASE_BIN: C:\msys64\usr
      MSYS_BASE: C:\msys64\mingw32
      MINGW_BASE: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1

install:
  - cmd: echo %Platform%
 # - cmd: set MINGW-W64_BASE=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0 
 # - cmd: set MINGW-W64_BASE=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
  - cmd: uname -a
  - cmd: mkdir C:\ibex
  - cmd: set PATH=%PATH%;%MINGW_BASE%\bin;%MSYS_BASE_BIN%\bin
  - cmd: set CPATH=%CPATH%;%MINGW_BASE%\include;%MSYS_BASE%\include
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;%MINGW_BASE%\lib;%MSYS_BASE%\lib
 # - cmd: pacman --noconfirm -S mingw-w64-i686-cppunit
 # - cmd: pacman --noconfirm -S mingw-w64-i686-lapack
 # - cmd: set PREFIX=%HOMEDRIVE%%HOMEPATH%
  - cmd: set PREFIX=C:\projects\ibex
 # - cmd: cd C:\projects\ && git clone git://anongit.freedesktop.org/git/libreoffice/cppunit/ 
 # - cmd: cd C:\projects\cppunit
 # - cmd: sh autogen.sh && sh configure && make && make check && make install
 # - cmd: set CPATH=%CPATH%;C:\projects\cppunit\include
 # - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;C:\projects\cppunit\lib
 # - cmd: cd
  

build_script:
  - cmd: python -x waf configure --interval-lib=%TEST_INTERVAL_LIB% --prefix=%PREFIX% --with-debug --with-ampl --with-optim  --lp-lib=clp
  - cmd: python -x waf install

test_script:
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig
  # We need to add the path to libcppunit in PATH
 # - cmd: set PATH=%PATH%;C:\msys64\mingw32\bin
  - cmd: python -x waf utest

on_failure:
  - cmd: cat __build__\config.log
  - cmd: cat __build__\utest_config.log
  - cmd: cat __build__\utest_run.log
