version: build{build}
image: Visual Studio 2015
configuration: Release
platform: x64 
  
environment:
  matrix:
    - TEST_INTERVAL_LIB: "gaol"
    - TEST_INTERVAL_LIB: "filib"

install:
  - cmd: echo %Platform%
  - cmd: set MINGW-W64_BASE=c:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1
  - cmd: set PATH=%MINGW-W64_BASE%\mingw32\bin;c:\msys64\usr\bin;%PATH%
  - cmd: uname -a
  - cmd: pacman --noconfirm -S mingw-w64-x86_64-cppunit
  - cmd: pacman --noconfirm -S mingw-w64-x86_64-lapack
  - cmd: set CPATH=%CPATH%;c:\msys64\mingw32\include
  - cmd: set LIBRARY_PATH=%LIBRARY_PATH%;c:\msys64\mingw32\lib
  - cmd: set PREFIX=%HOMEDRIVE%%HOMEPATH%

build_script:
  - cmd: python -x waf configure --interval-lib=%TEST_INTERVAL_LIB% --prefix=%PREFIX% --with-debug --with-optim  --lp-lib=clp --with-ampl
  - cmd: python -x waf install clean

test_script:
  - cmd: set PKG_CONFIG_PATH=%PREFIX%\share\pkgconfig
  # We need to add the path to libcppunit in PATH
  - cmd: set PATH=%PATH%;c:\msys64\mingw32\bin
  - cmd: python -x waf utest

on_failure:
  - cmd: cat __build__\config.log
  - cmd: cat __build__\utest_config.log
  - cmd: cat __build__\utest_run.log
